### ISSUE TITLE
Optional permissions for the extension

### ISSUE THREAD

**Issue by Mx-Glitter** [nickdenardis/social-visual-alt-text#11]
Thank you very much for your work!

I think it would be great to change the permissions model for this extension from all-or-nothing to being able to fine-tune which social media we want to enable it for. I don't know much about developing browser extensions but it looks like it should be feasible reading these articles for [Firefox](https://support.mozilla.org/en-US/kb/manage-optional-permissions-extensions) and for [Chrome](https://developer.chrome.com/docs/extensions/reference/permissions/#implementing-optional-permissions).

What do you think?

**Comment by nickdenardis** [comment]
Thanks for this! It is probably a good time to revisit the possible permissions needed and what the extension is currently asking for. 

Right now it only needs to read and write to the DOM for each social media site.

It does ask for them all upfront and enables the visual alt text for each unless you turn it off in the Options area for the extension:
https://github.com/nickdenardis/social-visual-alt-text#options

I need to ree-verify what the dialogs look like with the current manifest of what it is asking for when the extension is first installed.

If you have those dialogs, would you be able to provide them here?

**Comment by Mx-Glitter** [comment]
I can show you the dialogs for Firefox, I don't have visuals for Chrome right now as I have to install it first, but I can do it if you're unable to, let me know.

<details><summary>Installation dialog</summary>
<img width="429" alt="Screen Shot 2021-09-06 at 01 27 21" src="https://user-images.githubusercontent.com/4671739/132144321-a68459cf-681c-4390-9f6f-efc145fa6b8d.png">
</details>

<details><summary>Preferences dialog</summary>
<img width="667" alt="Screen Shot 2021-09-06 at 01 28 30" src="https://user-images.githubusercontent.com/4671739/132144327-02ff2f63-5a77-4a48-8b11-7f191444cee0.png">
</details>

The thing that makes it not optimal (I admit it's a bit nit-picky) is that you can enable/disable alt-text on individual social media in the extension preferences but the permissions to read/write are still globally on. The user has to trust the extension code not to read/write the social media that are disabled in the preferences.

**Comment by nickdenardis** [comment]
This is still on my radar. Working to find a good model for adding and removing permissions in real-time. The same permissions are available in the options dialog, but `optional_permissions` is the long-term goal so they can be selected when installing the extension.

**Comment by nickdenardis** [comment]
Since the introduction of Mastodon support, which could exist on any domain, the permission requirements have changed. The extension now requests all site permissions.

It will need to access each site moving forward to determine if the page is a Mastodon instance or not.
