### ISSUE TITLE
Twitter animated GIF container size increasing rapidly filling browser window

### ISSUE THREAD

**Issue by jakedolan** [nickdenardis/social-visual-alt-text#15]
Description:
Animated GIF container appears in timeline (or direct tweet), and the container starts to grow vertically.

Screen recording:
https://vimeo.com/741214740/c3cf661d2a

In the wrapping FIGURE tag, five DIVs deep there is a div whose padding-bottom (as a %) is growing continuously (but linearly). Example:
`<div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 12514.9%;"></div>`

Steps to Reproduce:
1. Log into Twitter
2. Go to any tweet with an animated GIF. (recording used this tweet: https://twitter.com/gif_plus/status/641807200936177665)

Other details:
I first noticed this in the last week or so. It is reproducible on my machine with both Chrome ( v104.0.5112.102 (latest)) and Firefox (v103.0.2 (latest). 

It was only reproducible when I am logged into Twitter. If I log out it is not present.

Disabling social-visual-alt-text resolved the problem. 
Disabling all extensions but social-visual-alt-text, the problem persists.

**Comment by nickdenardis** [comment]
Thanks for the report and the way to reproduce this!

I hit this same issue this morning, but then refreshing the page and scrolling through Twitter again, it didn't happen. 🤔

Working to move the injected code for Twitter to try to get this resolved now and in future Twitter HTML changes.

**Comment by nickdenardis** [comment]
The new version has been submitted to the Chrome and Firefox extension stores. It is currently waiting for approval.
