### ISSUE TITLE
Order of alts back-to-front for multi-image toots

### ISSUE THREAD

**Issue by patrickhlauke** [nickdenardis/social-visual-alt-text#23]
Just passing this on (and can confirm from my own testing): https://fedisabled.social/@Lachgas/110502133221548127

In short, for toots with multiple images, the visible alt blocks are presented in reverse order (from last to first) - presumably (though admittedly i've not looked at the code here) because the extension goes through images sequentially in order, but then always adds the latest alt it found directly after the image(s), meaning that later images it finds get their alt added *before* any preceding alts.

Original post about this uses https://chaos.social/@blinry/110501630260892140 as an example

![screenshot of the chaos.social/@blinry post, with four images, showing the visible alts underneath the images in reverse order](https://github.com/nickdenardis/social-visual-alt-text/assets/895831/c75ccb7e-6fbd-482a-a868-de11b106f111)

**Comment by nickdenardis** [comment]
Thanks for pointing this out! I'll get this re-ordered correctly soon here 😊

**Comment by patrickhlauke** [comment]
wondeful, thank you @nickdenardis

**Comment by nickdenardis** [comment]
Firefox version is published, Chrome version still being reviewed.

**Comment by patrickhlauke** [comment]
i'm afraid this problem seems to have reappeared (possibly as a result of other recent fixes)

for instance: https://sfba.social/@foxprimephotos/110689589131925729

[Screenshot of a mastodon post with two images, and the alt text underneath them in reverse order](https://github.com/nickdenardis/social-visual-alt-text/assets/895831/cdd36b18-46ee-4b8a-8d2c-868747a43640)
