### ISSUE TITLE
Mastodon ALTs are somehow "batched"

### ISSUE THREAD

**Issue by patrickhlauke** [nickdenardis/social-visual-alt-text#24]
Possibly as a side effect/bug caused by the fix to https://github.com/nickdenardis/social-visual-alt-text/issues/23 I'm now seeing (not consistently though, which is odd) cases where the alt text of various posts on mastodon are all batched/bunched up under one image in one of the posts. This is in the multicolumn view of Mastodon...

![Post showing three separate alt texts under a single image](https://github.com/nickdenardis/social-visual-alt-text/assets/895831/68eab157-add1-4d87-a10c-388b04ba673f)

![A few posts earlier in the timeline with ALT. the two images there are the ones whose alt was shown underneath the third image in the above screenshot](https://github.com/nickdenardis/social-visual-alt-text/assets/895831/13050642-0c03-4634-8fda-6ff34c6083d4)

**Comment by nickdenardis** [comment]
Good catch! I didn't try it in advanced mode, multicolumn. 

I'll investigate this further and get a fix together.

**Comment by magicalskye** [comment]
i also get this in the “regular” view, see screenshot

thanks btw for this add-on, it’s a real life saver for my poor eyes

![Screenshot_2023-06-19_09-51-41](https://github.com/nickdenardis/social-visual-alt-text/assets/28151473/67f9a1a6-4e2f-4004-a067-0d66b352a545)

**Comment by nickdenardis** [comment]
Pretty sure I got to the bottom of this issue now. The code is fixed and a new version is waiting for approval in the Chrome and Firefox webstores.

| Before | After |
|--------|--------|
| <img width="390" alt="Screenshot 2023-07-01 at 7 45 31 AM" src="https://github.com/nickdenardis/social-visual-alt-text/assets/37359/04648583-6631-4b2c-aaeb-806b5755aaa1"> | <img width="295" alt="Screenshot 2023-07-01 at 8 27 06 AM" src="https://github.com/nickdenardis/social-visual-alt-text/assets/37359/19ab1131-2260-413c-b633-0739c16e20d1"> |

It should be rolling out in the next few days.

**Comment by patrickhlauke** [comment]
great stuff, thank you @nickdenardis
